# Generated by Django 5.2.9 on 2026-01-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bio_user_created_at_user_desired_salary_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_introduction',
            field=models.FileField(blank=True, null=True, upload_to='video_profiles/'),
        ),
    ]
