# Generated by Django 5.2.9 on 2026-01-01 12:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_phone', models.CharField(blank=True, max_length=50)),
                ('candidate_resume', models.FileField(blank=True, null=True, upload_to='referral_resumes/')),
                ('job_title', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Why this candidate is a good fit')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('interviewing', 'Interviewing'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reward_paid', models.BooleanField(default=False)),
                ('reward_paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'company_referrals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('current', 'Current Employee'), ('former', 'Former Employee')], max_length=20)),
                ('job_title', models.CharField(max_length=200)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_life_balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('salary_benefits', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('job_security', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('management', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('culture', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('advice_to_management', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review_helpful',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='verification_documents',
            field=models.JSONField(blank=True, help_text='URLs to verification documents', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['slug'], name='companies_slug_e0676c_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_verified'], name='companies_is_veri_16da10_idx'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AddField(
            model_name='companyreferral',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyreferral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='companies.companyreview'),
        ),
        migrations.AddField(
            model_name='reviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='companyreferral',
            index=models.Index(fields=['referrer', '-created_at'], name='company_ref_referre_a344c7_idx'),
        ),
        migrations.AddIndex(
            model_name='companyreferral',
            index=models.Index(fields=['company', 'status'], name='company_ref_company_aa4f41_idx'),
        ),
        migrations.AddIndex(
            model_name='companyreferral',
            index=models.Index(fields=['candidate_email'], name='company_ref_candida_32087a_idx'),
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['company', '-overall_rating'], name='company_rev_company_c3d6de_idx'),
        ),
        migrations.AddIndex(
            model_name='companyreview',
            index=models.Index(fields=['-created_at'], name='company_rev_created_469f25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyreview',
            unique_together={('company', 'reviewer')},
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review'], name='review_help_review__606aca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
    ]
