# Generated by Django 5.2.9 on 2026-01-01 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('resume_parse', 'Resume Parsing'), ('job_match', 'Job Matching'), ('job_description', 'Job Description Generation'), ('search_parse', 'Search Query Parsing'), ('interview_questions', 'Interview Questions'), ('salary_insights', 'Salary Insights')], max_length=50)),
                ('input_tokens', models.IntegerField(default=0, help_text='Approximate input tokens')),
                ('output_tokens', models.IntegerField(default=0, help_text='Approximate output tokens')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_usage_lo_user_id_3b96bc_idx'), models.Index(fields=['service_type', '-created_at'], name='ai_usage_lo_service_32e2db_idx'), models.Index(fields=['-created_at'], name='ai_usage_lo_created_8b092b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterviewPrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(help_text='List of generated interview questions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='jobs.job')),
            ],
            options={
                'db_table': 'ai_interview_prep',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', '-created_at'], name='ai_intervie_job_id_ae57cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(help_text='Match score 0-100')),
                ('match_data', models.JSONField(help_text='Detailed match analysis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_matches', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_job_matches',
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['user', '-match_score'], name='ai_job_matc_user_id_ae3c10_idx'), models.Index(fields=['job', '-match_score'], name='ai_job_matc_job_id_fad19f_idx')],
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='ParsedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(help_text='Original resume text')),
                ('parsed_data', models.JSONField(help_text='Structured data extracted by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_parsed_resumes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_parsed_r_user_id_d707c5_idx')],
            },
        ),
    ]
